# Generated by Django 6.0.5 on 2026-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('attempted', 'Attempted'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=15)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='donations_d_status_ad9788_idx'), models.Index(fields=['order_id'], name='donations_d_order_i_248b4d_idx')],
            },
        ),
    ]
