# Generated by Django 4.2 on 2026-10-02 13:00

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create(
            username='admin',
            email='admin@speedtrust.org',
            password=make_password('SpeedTrust2026!'),
            is_superuser=True,
            is_staff=True,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donation_id_alter_donationallocation_id_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
