// src/components/Gallery/galleryData.js
import childrensImg from '../../assets/childrens.jpg';
import foodDriveImg from '../../assets/event_food_drive.jpg';
import schoolSuppliesImg from '../../assets/event_school_supplies.jpg';
import healthCampImg from '../../assets/event_health_camp.jpg';

export const galleryCategories = [
  { id: 'all', label: 'All Moments', icon: '🌟' },
  { id: 'education', label: 'Education & Learning', icon: '📚' },
  { id: 'nutrition', label: 'Nutrition & Daily Meals', icon: '🍲' },
  { id: 'arts', label: 'Arts & Creativity', icon: '🎨' },
  { id: 'sports', label: 'Sports & Play', icon: '⚽' },
  { id: 'celebrations', label: 'Celebrations & Festivals', icon: '🎉' },
  { id: 'healthcare', label: 'Healthcare & Wellness', icon: '🏥' },
  { id: 'community', label: 'Community & Outreach', icon: '🌱' },
];

export const galleryItems = [
  {
    id: 1,
    title: 'Bright Horizons: Smart Learning & Digital Literacy',
    category: 'education',
    categoryName: 'Education & Learning',
    aspect: 'tall',
    image: schoolSuppliesImg,
    fallbackImage: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80',
    date: 'February 2025',
    location: 'Speed Trust Learning Centre, Kallakurichi',
    likes: 142,
    donorSupport: 'Speed Trust Education Fund',
    author: 'Care Team',
    authorRole: 'Education Coordinator',
    summary: 'Empowering curious minds with modern study tools, textbooks, and interactive learning sessions.',
    story: 'At Speed Trust, we believe that education is the ultimate catalyst for breaking generational hardship. Our learning centre provides personalized tutoring, computer literacy modules, and STEM exploration kits for over 180 young students.',
    impact: '180+ Students Attending Daily Sessions',
    tags: ['#DigitalClassroom', '#EducationForAll', '#SpeedTrustKids']
  },
  {
    id: 2,
    title: 'Warm Smiles & Nutritious Mid-Day Feast',
    category: 'nutrition',
    categoryName: 'Nutrition & Daily Meals',
    aspect: 'square',
    image: foodDriveImg,
    fallbackImage: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80',
    date: 'January 2025',
    location: 'Community Dining Hall, Kallakurichi',
    likes: 218,
    donorSupport: 'Community Food Mission',
    author: 'Kitchen & Wellness Team',
    authorRole: 'Nutrition Care Specialist',
    summary: 'Freshly prepared wholesome meals packed with proteins, leafy vegetables, and whole grains served with love.',
    story: 'Nutrition is fundamental to every child’s cognitive development and physical vitality. Speed Trust operates daily nutrition drives ensuring zero malnutrition among rural children and destitute families.',
    impact: '250+ Nutritious Meals Served Daily',
    tags: ['#ZeroHunger', '#HealthyKids', '#NourishHope']
  },
  {
    id: 3,
    title: 'Joyful Childhood: Afternoon Playground Fun',
    category: 'sports',
    categoryName: 'Sports & Play',
    aspect: 'tall',
    image: childrensImg,
    fallbackImage: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80',
    date: 'March 2025',
    location: 'Speed Trust Trust Campus, Tamil Nadu',
    likes: 189,
    donorSupport: 'Youth Sports Initiative',
    author: 'Coach Selvam',
    authorRole: 'Sports & Physical Fitness Lead',
    summary: 'Laughter echoes across the playground as the kids engage in teamwork games, football drills, and traditional sports.',
    story: 'Play is the natural language of childhood. Our structured evening sports sessions foster confidence, camaraderie, resilience, and unbridled joy for children who have overcome challenging circumstances.',
    impact: '90+ Active Young Athletes',
    tags: ['#PlayTime', '#JoyOfChildhood', '#Teamwork']
  },
  {
    id: 4,
    title: 'Comprehensive Pediatric Health & Vision Camp',
    category: 'healthcare',
    categoryName: 'Healthcare & Wellness',
    aspect: 'wide',
    image: healthCampImg,
    fallbackImage: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    date: 'December 2024',
    location: 'Ka. Mamananthal Village Medical Centre',
    likes: 165,
    donorSupport: 'Dr. Ramesh Kumar & Volunteer Medics',
    author: 'Dr. Aruna & Team',
    authorRole: 'Visiting Pediatrician',
    summary: 'Routine pediatric evaluations, dental hygiene kits, eye tests, and micronutrient supplements distributed free of charge.',
    story: 'In partnership with selfless volunteer doctors, Speed Trust hosts bi-monthly health screening camps. Preventive care, early diagnosis, and warm emotional reassurance ensure all children grow up healthy and safe.',
    impact: '320+ Children Screened & Supported',
    tags: ['#HealthcareCamp', '#ChildWellness', '#HealthySmiles']
  },
  {
    id: 5,
    title: 'Coloring Dreams: Young Artists in Action',
    category: 'arts',
    categoryName: 'Arts & Creativity',
    aspect: 'tall',
    image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80',
    fallbackImage: '/img1.jpg',
    date: 'February 2025',
    location: 'Speed Trust Creative Studio',
    likes: 274,
    donorSupport: 'Art for Hope Foundation',
    author: 'Meenakshi R.',
    authorRole: 'Art & Craft Mentor',
    summary: 'Splashing vibrant colors on canvas, discovering creative expression, and building self-confidence through art.',
    story: 'Through weekly drawing, painting, and craft workshops, our children channel their thoughts, express inner dreams, and create stunning artworks that reflect their resilience and cheerful optimism.',
    impact: '60+ Creative Art Portfolios Created',
    tags: ['#CreativeMinds', '#ArtHeals', '#YoungArtists']
  },
  {
    id: 6,
    title: 'Tribal Village School Support & Study Kits',
    category: 'community',
    categoryName: 'Community & Outreach',
    aspect: 'wide',
    image: '/tribalSchool.jpg',
    fallbackImage: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    date: 'November 2024',
    location: 'Kalvarayan Hills, Villupuram / Kallakurichi',
    likes: 198,
    donorSupport: 'Speed Trust Tribal Outreach',
    author: 'Karthik N.',
    authorRole: 'Field Coordinator',
    summary: 'Bringing quality educational aids, solar study lamps, and warm clothing to remote tribal hamlet schools.',
    story: 'Reaching the most remote hamlets in the hills, our volunteer team traverses difficult terrains to deliver educational supplies, nutritious snacks, and clean water solutions to underserved tribal children.',
    impact: '12 Tribal Hamlets Reached',
    tags: ['#TribalWelfare', '#LastMileReach', '#SpeedTrustImpact']
  },
  {
    id: 7,
    title: 'Festival of Lights: Deepavali Celebration with Family',
    category: 'celebrations',
    categoryName: 'Celebrations & Festivals',
    aspect: 'square',
    image: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80',
    fallbackImage: '/img1.jpg',
    date: 'November 2024',
    location: 'Speed Trust Main Sanctuary',
    likes: 310,
    donorSupport: 'Generous Festival Patrons',
    author: 'Speed Trust Care Team',
    authorRole: 'Campus Administrators',
    summary: 'New clothes, sparkling lights, delicious homemade sweets, and endless joy celebrating togetherness.',
    story: 'Every festival at Speed Trust is celebrated like a big loving family. Children receive tailor-made festive attire, participate in cultural dance routines, and share sweets with elderly residents from our shelter.',
    impact: '150+ Kids & Elders Celebrated Together',
    tags: ['#Deepavali2024', '#FamilyOfLove', '#CelebrationOfHope']
  },
  {
    id: 8,
    title: 'Clean Water Mission: Borewell & Pure RO Installation',
    category: 'community',
    categoryName: 'Community & Outreach',
    aspect: 'tall',
    image: '/borewellProgram.jpg',
    fallbackImage: 'https://images.unsplash.com/photo-1541976590-713941681591?auto=format&fit=crop&w=800&q=80',
    date: 'January 2025',
    location: 'Ka.Mamananthal Village Facility',
    likes: 153,
    donorSupport: 'Pure Water For All Project',
    author: 'Infrastructure Wing',
    authorRole: 'Community Development',
    summary: 'Ensuring safe, continuous drinking water supply for children, shelter residents, and neighboring families.',
    story: 'Access to safe drinking water is a fundamental right. Speed Trust installed deep-water filtration units and solar pumping infrastructure, eliminating waterborne diseases and providing pure hydration for hundreds daily.',
    impact: '500+ Daily Beneficiaries of Clean Water',
    tags: ['#CleanWater', '#HealthFirst', '#SustainableCare']
  },
  {
    id: 9,
    title: 'Special Care & Inclusive Learning for Differently Abled',
    category: 'healthcare',
    categoryName: 'Healthcare & Wellness',
    aspect: 'square',
    image: '/mentallyDisabled.jpg',
    fallbackImage: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=800&q=80',
    date: 'October 2024',
    location: 'Speed Trust Special Care Wing',
    likes: 227,
    donorSupport: 'Inclusive Hearts Donor Guild',
    author: 'Special Educator Radha',
    authorRole: 'Rehabilitation Specialist',
    summary: 'Dedicated therapy, sensory stimulation games, and unconditional empathy for children with unique challenges.',
    story: 'We provide specialized occupational therapy, speech therapy, and personalized adaptive learning tools, empowering children with intellectual and developmental challenges to thrive with dignity and independence.',
    impact: '45+ Children Receiving Daily Specialized Care',
    tags: ['#SpecialCare', '#InclusionMatters', '#UnconditionalLove']
  },
  {
    id: 10,
    title: 'Annual Day Drama & Classical Music Recital',
    category: 'celebrations',
    categoryName: 'Celebrations & Festivals',
    aspect: 'wide',
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    fallbackImage: '/img1.jpg',
    date: 'January 2025',
    location: 'Kallakurichi Municipal Auditorium',
    likes: 184,
    donorSupport: 'Cultural Heritage Circle',
    author: 'Music & Cultural Guild',
    authorRole: 'Event Director',
    summary: 'Children dazzle the audience with inspiring theatre plays depicting kindness, harmony, and dreams of the future.',
    story: 'Our annual showcase gives every child the spotlight to shine. From stage set design to singing and choreography, students learn public speaking, coordination, and the confidence to stand tall before thousands.',
    impact: '400+ Audience Members Wowed',
    tags: ['#AnnualDay', '#YoungTalent', '#ShiningBright']
  },
  {
    id: 11,
    title: 'Vocational Skill Building & Tailoring Workshops',
    category: 'education',
    categoryName: 'Education & Learning',
    aspect: 'tall',
    image: 'https://images.unsplash.com/photo-1558021212-51b6ecfa0db9?auto=format&fit=crop&w=800&q=80',
    fallbackImage: '/construction.jpg',
    date: 'December 2024',
    location: 'Speed Trust Skill Academy',
    likes: 176,
    donorSupport: 'Empower Youth Grant',
    author: 'Saraswathi Ammal',
    authorRole: 'Vocational Trainer',
    summary: 'Equipping older teens and youth with practical livelihood skills in tailoring, basic electricals, and craft creation.',
    story: 'Transitioning into adulthood requires economic self-reliance. Our skill labs provide certified vocational training programs, ensuring young adults graduate into stable, dignified employment opportunities.',
    impact: '65+ Youth Certified in 2024',
    tags: ['#SkillTraining', '#YouthEmpowerment', '#SelfReliance']
  },
  {
    id: 12,
    title: 'Intergenerational Harmony: Kids & Elders Bonding',
    category: 'community',
    categoryName: 'Community & Outreach',
    aspect: 'square',
    image: '/oldageHome.jpg',
    fallbackImage: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=800&q=80',
    date: 'February 2025',
    location: 'Speed Trust Senior Home & Children Campus',
    likes: 295,
    donorSupport: 'Universal Kinship Initiative',
    author: 'Trust Operations',
    authorRole: 'Community Care Officer',
    summary: 'Storytelling sessions where grandfatherly wisdom meets the sparkling curiosity of young children.',
    story: 'One of Speed Trust’s most cherished programs connects abandoned seniors with orphaned children. The elders find purpose and affectionate grandkids, while the children receive the boundless love of caring grandparents.',
    impact: 'A Unified Family of 110 Souls',
    tags: ['#IntergenerationalLove', '#ElderCare', '#OneBigFamily']
  },
  {
    id: 13,
    title: 'Green Earth: Tree Planting & Eco-Warrior Club',
    category: 'community',
    categoryName: 'Community & Outreach',
    aspect: 'wide',
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    fallbackImage: childrensImg,
    date: 'January 2025',
    location: 'Speed Trust Eco Garden, Kallakurichi',
    likes: 167,
    donorSupport: 'Eco Youth Circle',
    author: 'Green Guardians Club',
    authorRole: 'Environmental Education Lead',
    summary: 'Kids plant indigenous shade trees, nurture organic vegetable patches, and learn sustainable living values.',
    story: 'Children learn hands-on permaculture and botany by tending to our organic kitchen garden. The fresh tomatoes, spinach, and herbs harvested directly enrich the nutritional quality of our daily trust meals.',
    impact: '350+ Saplings Planted & Maintained',
    tags: ['#EcoWarriors', '#GreenCampus', '#SustainableFuture']
  },
  {
    id: 14,
    title: 'Mini Olympics & Athletics Championship',
    category: 'sports',
    categoryName: 'Sports & Play',
    aspect: 'tall',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    fallbackImage: childrensImg,
    date: 'November 2024',
    location: 'District Sports Ground, Kallakurichi',
    likes: 231,
    donorSupport: 'Champion Spirit Sponsors',
    author: 'Sports Committee',
    authorRole: 'Athletic Lead',
    summary: '100m sprints, relay races, high jumps, and joyous medal ceremonies celebrating effort and sportsmanship.',
    story: 'Speed Trust children took home 14 district-level athletic medals this year! Our sports curriculum proves that with proper coaching and unwavering belief, underprivileged youth can conquer any sporting arena.',
    impact: '14 Medals Won at District Level',
    tags: ['#FutureChampions', '#Sportsmanship', '#WinningHearts']
  },
  {
    id: 15,
    title: 'Clay Sculpting & Traditional Pottery Workshop',
    category: 'arts',
    categoryName: 'Arts & Creativity',
    aspect: 'square',
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    fallbackImage: '/img1.jpg',
    date: 'December 2024',
    location: 'Artisan Workshop Hall',
    likes: 149,
    donorSupport: 'Traditional Crafts Collective',
    author: 'Master Potter Murugan',
    authorRole: 'Guest Artisan',
    summary: 'Tactile learning, pottery wheels, and crafting traditional clay lamps and decorative pots.',
    story: 'Connecting children with indigenous crafts builds fine motor skills, patience, and appreciation for traditional Tamil artisans. The handcrafted clay diyas were gifted to community donors during festival season.',
    impact: '80+ Handcrafted Sculptures Created',
    tags: ['#TraditionalArts', '#PotteryMagic', '#TactileLearning']
  },
  {
    id: 16,
    title: 'Pongal Harvest Festival & Sweet Rice Cooking',
    category: 'celebrations',
    categoryName: 'Celebrations & Festivals',
    aspect: 'tall',
    image: 'https://images.unsplash.com/photo-1579618218290-24a26f63a728?auto=format&fit=crop&w=800&q=80',
    fallbackImage: foodDriveImg,
    date: 'January 2025',
    location: 'Speed Trust Village Courtyard',
    likes: 342,
    donorSupport: 'Pongal Joy Patrons',
    author: 'Speed Trust Care Team',
    authorRole: 'Cultural Organizers',
    summary: 'Overflowing clay pots of sweet Pongal, colorful Kolam rangolis, sugarcane treats, and joyful folk dance.',
    story: 'Pongalo Pongal! The campus came alive in yellow and orange hues as students dressed in traditional veshtis and pattu pavadais cheered when the sweet milk boiled over, symbolizing prosperity and gratitude.',
    impact: '300+ Participants in Traditional Festivities',
    tags: ['#Pongal2025', '#TamilCulture', '#HarvestBlessings']
  }
];
